# Generated by Django 5.0.6 on 2024-06-16 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Model_Mashine_Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tip', models.CharField(choices=[('TURNING', 'Turning'), ('DRILLING', 'Drilling'), ('GRINDING', 'Grinding'), ('COMBINED', 'Combined'), ('GEAR_PROCESSING', 'Gear_Processing'), ('MILLING', 'Milling'), ('PLANING', 'Planing'), ('SPLIT', 'Split'), ('DIFFERENT', 'Different')], default='Different', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('characteristic', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
            ],
            options={
                'verbose_name_plural': 'Models',
            },
        ),
    ]
