# Generated by Django 5.0.6 on 2024-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_mashine_tools',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
