# Generated by Django 5.0.6 on 2024-06-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_model_mashine_tools_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_mashine_tools',
            options={'ordering': ['company', 'price'], 'verbose_name_plural': 'Models'},
        ),
    ]
